name: dartTelegaBot

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0

dependencies: 
  convert: ^3.0.1
  html: ^0.15.0
  http: ^0.13.4
  postgres: ^2.4.3
  teledart: ^0.3.2 
